/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 4, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/
let num1 = 0;
let num2 = 1;
let numN = 0;

let index = 0;
let sum = 0;

while (numN < 4000000) {
    numN = num1 + num2;
    console.log(numN);

    if (numN % 2 === 0) {
        sum += numN;
        console.log(sum)
    }
    num1 = num2;
    console.log(num1);
    
    num2 = numN;
    console.log(num2);

    // index++;
}
console.log(sum);
